version: "3.7"
services:
  cpuminer:
    container_name: cpuminer
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.cpuminer
    image: cpuminer
    volumes:
      - ../../config/cpuminer.conf:/app/cpuminer.conf
    # entrypoint: ./minerd --algo=scrypt --url=stratum+tcp://stratum:3333
    entrypoint: ./minerd -c /app/cpuminer.conf --coinbase-addr=n44dzdqdqcihkVRAW5BRRXFAFqRwjJYqBv
    networks:
      - bitcoin