version: "3.7"

services:
  bitcoind:
    extends:
      file: dockerfile/bitcoind/docker-compose.yml
      service: bitcoind
    networks:
      - bitcoin
  bitcoin-node-manager:
    image: php:8.2-apache
    container_name: bitcoin-node-manager
    ports:
      - 8001:80
    volumes:
      - ./bitcoin-node-manager:/var/www/html
    networks: 
      - bitcoin
  bitcoin-node-manager2:
    image: php:8.2-apache
    container_name: bitcoin-node-manager2
    ports:
      - 8002:80
    volumes:
      - ./bitcoin-node-manager2:/var/www/html
    networks: 
      - bitcoin
  cpuminer:
    extends:
      file: dockerfile/cpuminer/docker-compose.yml
      service: cpuminer
    networks:
      - bitcoin
  cgminer:
    extends:
      file: dockerfile/cgminer/docker-compose.yml
      service: cgminer
    networks:
      - bitcoin
  bfgminer:
    extends:
      file: dockerfile/bfgminer/docker-compose.yml
      service: bfgminer
    networks:
      - bitcoin
  stratum:
    extends:
      file: dockerfile/stratum/docker-compose.yml
      service: stratum
    networks:
      - bitcoin
  stratumdb:
    extends:
      file: dockerfile/stratumdb/docker-compose.yml
      service: stratumdb
    networks:
      - bitcoin
  litecoind:
    extends:
      file: dockerfile/litecoin/docker-compose.image.yml
      service: litecoind
    networks:
      - bitcoin
  litecoind2:
    extends:
      file: dockerfile/litecoin2/docker-compose.image.yml
      service: litecoind2
    networks:
      - bitcoin
  memcached:
      container_name: memcached
      image: memcached:latest
      ports:
        - 11211:11211
      volumes:
        - ./memcached:/var/lib
      healthcheck:
        test: ''
      networks:
        - bitcoin
  mpos:
    extends:
      file: dockerfile/mpos/docker-compose.yml
      service: mpos
    networks:
      - bitcoin
networks:
  bitcoin:
    name: bitcoin
    driver: bridge