version: "3.7"
services:
  bfgminer:
    container_name: bfgminer
    build:
      context: .
      dockerfile: Dockerfile.bfgminer
    image: bfgminer
    entrypoint: ./bfgminer -S opencl:auto -S cpu:auto --generate-to=n3kXKzaNUhWCsvKyKPJcJXHjcVW9J4wAuA
    volumes:
      - ../../config/bfgminer.conf:/app/bfgminer.conf
    networks:
      - bitcoin