version: "3.7"
services:
  litecoind2:
    container_name: litecoind2
    image: aofiee/litecoin_core:latest
    ports:
      - 7332:9332
      - 7333:9333 
      - 17332:19332 
      - 17333:19333
      - 17443:19443
      - 17444:19444
    volumes:
      - ../../config/litecoin2.conf:/data/litecoin.conf
      - ../../litecoin-data2:/home/litecoin/data
    restart: always
    entrypoint: ["litecoind"]
    command:
      -chain=regtest
      -printtoconsole
      -dnsseed=0
      -conf=/data/litecoin.conf
      -datadir=/home/litecoin/data
    networks:
      - bitcoin