version: "3.7"
services:
  bitcoind:
      image: cryptodockerhub/bitcoin-core:latest
      container_name: bitcoind
      restart: always
      ports:
        - 8332:8332
        - 8333:8333
        - 18332:18332
        - 18333:18333
        - 18443:18443
        - 18444:18444
      volumes:
        - ../../bitcore-data:/home/coinuser/.bitcoin
        - ../../config/bitcoin.conf:/data/config.conf
      command: 
        -chain=regtest
        -printtoconsole
        -dnsseed=0
        -fixedseeds=0
        -conf=/data/config.conf
      networks:
        - bitcoin